"""Summary-table building and its HTML and PDF rendering.

`_build_summary` assembles the per-model metric and hyperparameter rows; the
generators write them as a styled HTML page (layout in
``templates/report.html``) and as a PDF with one table per page.
"""

import math
from importlib import resources

import matplotlib

import matplotlib.pyplot as plt
from jinja2 import Template
from matplotlib.backends.backend_pdf import PdfPages

from AaltoAD.report import cli, metrics
import csv
import os

# HTML layout for the report page, kept in a template file rather than a string.
_TEMPLATE = resources.files("AaltoAD.report") / "templates" / "report.html"


# columns that can be displayed in the tables the report builds
DISPLAY_COLUMNS = ["eval_time", "calibration_loss"]


for _m in cli.METHOD_METRICS:
    DISPLAY_COLUMNS.append(_m)
    DISPLAY_COLUMNS.append(f"{_m} (PA)")


# Slim metric set for presentation tables. Each entry is (column_label, dotted_path_or_callable).
SLIDE_COLUMNS = [
    ("POT F1", "pot.f1"),
    ("POT F1 (PA)", "pot_expanded.f1"),
    ("POT FPR", "pot.fpr"),
    ("POT latency", "pot.p_latency"),
    ("Oracle F1", "oracle.f1"),
    ("Eval time (s)", "eval_time"),
]

# Unlabeled mode: alternate slim column spec.
UNLABELED_SLIDE_COLUMNS = [
    ("Detected", metrics._detected),
    ("Detection rate", metrics._detection_rate),
    ("Threshold", "pot.threshold"),
    ("Eval time (s)", "eval_time"),
]

# Cross-case overview: one table per metric, as (file suffix, caption phrase,
# metric name under cli.THRESHOLD_METHOD). Split by metric because a single table of
# model x case x three metrics is unreadable at this width.
OVERVIEW_TABLES = [
    ("f1", "F1", "f1"),
    ("fpr", "false positive rate", "fpr"),
    ("latency", "detection latency in time steps", "p_latency"),
]


def _generate_latex(
    dataset,
    metric,
    by_model,
    output_path,
    unlabeled=False,
    threshold_method=cli.THRESHOLD_METHOD,
    order=None,
    columns=cli.TABLE_COLUMNS,
    blocks=cli.TABLE_BLOCKS,
):
    """Write a LaTeX file with two tabular blocks (metrics + hyperparameters).

    `threshold_method` names the threshold block the columns are read from and
    `columns` which ones appear (see `_latex_columns`) and `blocks` how many
    models are set side by side per row.
    Designed to be ``\\input``-ed inside a user-provided ``table`` float —
    no float wrapper is emitted.
    """
    sort_metric = metrics._table_sort_metric(metric)
    lower_is_better = sort_metric in metrics.LOWER_IS_BETTER
    missing_sort_val = float("inf") if lower_is_better else float("-inf")

    slide_cols = (
        UNLABELED_SLIDE_COLUMNS
        if unlabeled
        else _latex_columns(threshold_method, columns)
    )

    # Slim metrics table (oracle-threshold metrics, see LATEX_COLUMNS).
    metric_rows = []
    for model, results in by_model.items():
        best = metrics._best_result(results, metric)
        row = {"model": model}
        for label, path_or_fn in slide_cols:
            if best:
                row[label] = metrics._fmt_metric(best, path_or_fn, threshold_method)
            else:
                row[label] = "N/A"
        try:
            sort_val = (
                float(metrics._get(best, sort_metric)) if best else missing_sort_val
            )
        except (TypeError, ValueError):
            sort_val = missing_sort_val
        if sort_val != sort_val:
            sort_val = missing_sort_val
        metric_rows.append((sort_val, row))
    _sort_rows(metric_rows, order, lower_is_better, key="model")
    metric_rows = [r for _, r in metric_rows]
    metric_cols = ["model"] + [c for c, _ in slide_cols]

    parts = [
        f"% Auto-generated by AaltoAD.report — dataset={dataset}, metric={cli.metric_display(metric)}, "
        f"threshold_method={threshold_method}",
        _latex_tabular(metric_cols, metric_rows, blocks=blocks),
        "",
    ]
    with open(output_path, "w") as f:
        f.write("\n".join(parts))
    print(f"LaTeX summary written to {output_path}")


def _generate_overview_latex(
    by_dataset,
    metric,
    output_dir,
    threshold_method=cli.THRESHOLD_METHOD,
    model_order=None,
):
    """Write one model-by-test-case table per entry in `OVERVIEW_TABLES`.

    Rows are models and columns test cases (there are far more models than
    cases). Every table shares one row order — `model_order` again, each of its
    metrics averaged over the cases — so the three can be read side by side.
    Values come from the `threshold_method` block of each model's selected run,
    the same numbers the per-case summary tables show.

    A latency cell is an em dash when the model produced no true positives on
    that case: `segment_latency` charges an undetected segment its full length,
    which would otherwise read as a real (very slow) detection.
    """
    model_order = cli.metric_list(metric if model_order is None else model_order)
    cases = sorted({_case_id(ds) for ds in by_dataset}, key=_case_sort_key)
    best = {}
    for dataset, by_model in by_dataset.items():
        case = _case_id(dataset)
        for model, results in by_model.items():
            result = metrics._best_result(results, metric)
            if result is not None:
                best[(model, case)] = result
    models = {model for model, _ in best}

    def mean_rank_key(model):
        """`metrics._rank_key` with each metric averaged over the cases the model ran on."""
        keys = [
            metrics._rank_key(best[(model, case)], model_order, threshold_method)
            for case in cases
            if (model, case) in best
        ]
        if not keys:
            return tuple(float("inf") for _ in model_order)
        return tuple(sum(values) / len(values) for values in zip(*keys))

    order = sorted(models, key=lambda model: (mean_rank_key(model), model))

    def cell(model, case, name):
        result = best.get((model, case))
        if result is None:
            return "N/A"
        return metrics._fmt_metric(
            result, f"{threshold_method}.{name}", threshold_method
        )

    os.makedirs(output_dir, exist_ok=True)
    for suffix, phrase, name in OVERVIEW_TABLES:
        rows = [
            {"model": model, **{case: cell(model, case, name) for case in cases}}
            for model in order
        ]
        output_path = os.path.join(output_dir, f"overview_{suffix}.tex")
        with open(output_path, "w") as f:
            f.write(
                "\n".join(
                    [
                        f"% Auto-generated by AaltoAD.report — {phrase} per model and test case, "
                        f"threshold_method={threshold_method}, rows ordered by mean F1",
                        _latex_tabular(["model"] + cases, rows),
                        "",
                    ]
                )
            )
        print(f"Overview table written to {output_path}")


def _case_sort_key(case_id):
    """Natural order for case ids, so 1.2 < 2.1.1 < 2.2.1 < 3.3.2 rather than string order."""
    return [
        (0, int(part), "") if part.isdigit() else (1, 0, part)
        for part in case_id.split(".")
    ]


def _case_id(dataset):
    """Short test-case id for a dataset name: TOL_DNV_1_1 -> '1.1', TOL_2_2_1 -> '2.2.1'."""
    name = dataset
    for prefix in ("TOL_", "DNV_"):
        if name.startswith(prefix):
            name = name[len(prefix) :]
    return name.replace("_", ".")


def _latex_tabular(columns, rows, caption=None, label=None, blocks=1):
    """Render a tabular block (no surrounding table float).

    With `blocks` > 1 the column set is repeated that many times side by side,
    separated by a wide gap, and the rows are dealt into them by
    `_blocked_rows` — a narrow table set two-up is half as tall.
    """
    blocks = max(1, blocks)
    one = "l" + "r" * (len(columns) - 1)
    align = r"@{\qquad}".join([one] * blocks)
    header = " & ".join([" & ".join(_latex_escape(c) for c in columns)] * blocks)

    lines = []
    if caption or label:
        lines.append("% " + (caption or "") + (f"  [{label}]" if label else ""))
    lines.append(r"\begin{tabular}{" + align + r"}")
    lines.append(r"\hline")
    lines.append(header + r" \\")
    lines.append(r"\hline")
    for line in _blocked_rows(rows, blocks):
        cells = []
        for row in line:
            cells.extend(_latex_escape(row.get(c, "")) if row else "" for c in columns)
        lines.append(" & ".join(cells) + r" \\")
    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    return "\n".join(lines)


def _blocked_rows(rows, blocks):
    """Split `rows` into `blocks` side-by-side columns, filled top to bottom.

    Returns a list of tuples, one per printed line, each holding the row of
    every block (None where a block has run out). Column-major, so reading down
    the first block and continuing down the second follows the row order.
    """
    if blocks < 2 or not rows:
        return [(row,) for row in rows]
    height = -(-len(rows) // blocks)  # ceiling division
    columns = [rows[i * height : (i + 1) * height] for i in range(blocks)]
    return [
        tuple(column[i] if i < len(column) else None for column in columns)
        for i in range(height)
    ]


def _latex_escape(s):
    """Escape LaTeX special characters in a string cell."""
    if s is None:
        return ""
    s = str(s)
    repl = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    out = []
    for ch in s:
        out.append(repl.get(ch, ch))
    return "".join(out)


def _generate_hp_markdown(dataset, metric, by_model, output_path, order=None):
    """One line per model listing its best-result hyperparameters."""
    sort_metric = metrics._table_sort_metric(metric)
    lower_is_better = sort_metric in metrics.LOWER_IS_BETTER
    missing_sort_val = float("inf") if lower_is_better else float("-inf")

    lines = [
        f"# Hyperparameters — {dataset}",
        f"_Best result per model by {cli.metric_display(metric)}_",
        "",
    ]
    entries = []
    for model, results in by_model.items():
        best = metrics._best_result(results, metric)
        hp = best.get("applied_hyperparameters", {}) if best else {}
        try:
            sort_val = (
                float(metrics._get(best, sort_metric)) if best else missing_sort_val
            )
        except (TypeError, ValueError):
            sort_val = missing_sort_val
        if sort_val != sort_val:
            sort_val = missing_sort_val
        parts = ", ".join(f"{k}={metrics._fmt(v)}" for k, v in sorted(hp.items()))
        entries.append(
            (
                sort_val,
                {"model": model},
                f"- **{model}**: {parts if parts else '(defaults)'}",
            )
        )
    _sort_rows(entries, order, lower_is_better, key="model")
    lines.extend(line for _, _row, line in entries)

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Hyperparameter summary written to {output_path}")


def _generate_csv(dataset, metric, by_model, output_path, unlabeled=False, order=None):
    """One row per model, slim metric set; selected and ordered by `metric`
    (falling back to F1 ordering for non-comparable metrics)."""
    sort_metric = metrics._table_sort_metric(metric)
    lower_is_better = sort_metric in metrics.LOWER_IS_BETTER
    missing_sort_val = float("inf") if lower_is_better else float("-inf")

    slide_cols = UNLABELED_SLIDE_COLUMNS if unlabeled else SLIDE_COLUMNS
    rows = []
    for model, results in by_model.items():
        best = metrics._best_result(results, metric)
        row = {"model": model}
        for label, path_or_fn in slide_cols:
            if best:
                row[label] = metrics._fmt(metrics._col_value(best, path_or_fn))
            else:
                row[label] = "N/A"
        try:
            sort_val = (
                float(metrics._get(best, sort_metric)) if best else missing_sort_val
            )
        except (TypeError, ValueError):
            sort_val = missing_sort_val
        if sort_val != sort_val:  # NaN
            sort_val = missing_sort_val
        rows.append((sort_val, row))
    _sort_rows(rows, order, lower_is_better, key="model")

    with open(output_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["model"] + [c for c, _ in slide_cols])
        writer.writeheader()
        for _, row in rows:
            writer.writerow(row)
    print(f"CSV summary written to {output_path}")


def _latex_columns(method=cli.THRESHOLD_METHOD, columns=cli.TABLE_COLUMNS):
    """Summary-table columns reading the `method` threshold block.

    `columns` names entries of `cli.TABLE_COLUMN_SPECS`; an unknown name is read as
    a metric of the method's block so a column can be asked for without being
    listed there. Raises nothing — an absent metric simply renders as N/A.
    """
    specs = []
    for name in cli.table_column_list(columns):
        header, path = cli.TABLE_COLUMN_SPECS.get(name, (name, "{method}." + name))
        specs.append((header, path.format(method=method)))
    return specs


def _sort_rows(rows, order, lower_is_better, key="model"):
    """Sort ``(sort_value, row, ...)`` tuples in place.

    With `order` (``{model: position}``) the report's one model order wins;
    without it, rows fall back to sorting by their own metric value.
    """
    if order is not None:
        rows.sort(key=lambda t: order.get(t[1][key], len(order)))
    else:
        rows.sort(key=lambda t: t[0], reverse=not lower_is_better)


matplotlib.use("Agg")


def _sort_grouped(grouped, order, lower_is_better):
    """`_sort_rows` for `_build_summary`'s ``(sort_value, method_rows, hp_row)`` tuples."""
    if order is not None:
        grouped.sort(key=lambda t: order.get(t[2]["row"], len(order)))
    else:
        grouped.sort(key=lambda t: t[0], reverse=not lower_is_better)


def _build_summary(by_model, metric, unlabeled=False, order=None):
    """Build metric rows and hyperparameter rows for best result per model.

    In labeled mode (unlabeled=False):
        Each model produces two metric rows — one for `pot`, one for `oracle` —
        where each numeric column appears twice: raw (point-wise) and PA
        (point-adjusted, i.e. segment-expanded). The row label is "<model> / <method>".

    In unlabeled mode (unlabeled=True):
        Each model produces a single row with columns: detected, detection rate,
        threshold, calibration_loss, eval_time.

    Sort order is by the row whose metric path matches the --metric argument.
    Returns (metric_rows, hp_rows, all_hp_keys, display_columns).
    """
    metric_rows = []
    hp_rows = []
    all_hp_keys = []
    seen_hp = set()

    # Collect hyperparameter keys from *every* result, not just the best. This
    # ensures any column that's ever been swept (e.g. `epochs` added later)
    # appears in the table even when a given model's best result predates it.
    for results in by_model.values():
        for r in results:
            for k in r.get("applied_hyperparameters", {}).keys():
                if k not in seen_hp:
                    all_hp_keys.append(k)
                    seen_hp.add(k)

    # Single fallback metric for the unlabeled path, which has no detections to
    # rank by; everywhere else `order` decides.
    sort_metric = _table_sort_metric(metric)
    lower_is_better = sort_metric in metrics.LOWER_IS_BETTER
    missing_sort_val = float("inf") if lower_is_better else float("-inf")

    if unlabeled:
        display_columns = [
            "detected",
            "detection rate",
            "threshold",
            "calibration_loss",
            "eval_time",
        ]
        grouped = []
        for model, results in by_model.items():
            best = metrics._best_result(results, metric)
            row = {"row": model}
            if best:
                row["detected"] = metrics._fmt(_detected(best))
                row["detection rate"] = metrics._fmt(_detection_rate(best))
                row["threshold"] = metrics._fmt(metrics._get(best, "pot.threshold"))
                row["calibration_loss"] = metrics._fmt(
                    metrics._get(best, "calibration_loss")
                )
                row["eval_time"] = metrics._fmt(metrics._get(best, "eval_time"))
            else:
                for c in display_columns:
                    row[c] = "N/A"
            try:
                sort_val = (
                    float(metrics._get(best, sort_metric)) if best else missing_sort_val
                )
                if math.isnan(sort_val):
                    sort_val = missing_sort_val
            except (TypeError, ValueError):
                sort_val = missing_sort_val
            h_row = {"row": model}
            hp = best.get("applied_hyperparameters", {}) if best else {}
            for k in all_hp_keys:
                h_row[k] = metrics._fmt(hp[k]) if k in hp else ""
            grouped.append((sort_val, [row], h_row))
        _sort_grouped(grouped, order, lower_is_better)
        for _, rows, h_row in grouped:
            metric_rows.extend(rows)
            hp_rows.append(h_row)
        return metric_rows, hp_rows, all_hp_keys, display_columns

    # Labeled mode
    display_columns = DISPLAY_COLUMNS

    # Order by the selection metric when comparable across models (dotted
    # metrics like oracle.f1); otherwise fall back to SUMMARY_SORT_METRIC.
    table_sort = _table_sort_metric(metric)
    lower_is_better = table_sort in metrics.LOWER_IS_BETTER
    missing_sort_val = float("inf") if lower_is_better else float("-inf")
    sort_method, sort_sep, sort_metric = table_sort.partition(".")

    grouped = []  # list of (sort_value, [method_rows], hp_row)
    for model, results in by_model.items():
        best = metrics._best_result(results, metric)
        method_rows = []
        sort_val = missing_sort_val
        for method in cli.METHODS:
            row = {"row": f"{model} / {method}"}
            for m in cli.METHOD_METRICS:
                row[m] = (
                    metrics._fmt(metrics._get(best, f"{method}.{m}")) if best else "N/A"
                )
                row[f"{m} (PA)"] = (
                    metrics._fmt(metrics._get(best, f"{method}_expanded.{m}"))
                    if best
                    else "N/A"
                )
            row["eval_time"] = (
                metrics._fmt(metrics._get(best, "eval_time")) if best else "N/A"
            )
            row["calibration_loss"] = (
                metrics._fmt(metrics._get(best, "calibration_loss")) if best else "N/A"
            )
            if sort_sep and method == sort_method:
                try:
                    sv = (
                        float(row[sort_metric])
                        if row.get(sort_metric) not in ("N/A", "NaN", None)
                        else missing_sort_val
                    )
                    if math.isnan(sv):
                        sv = missing_sort_val
                    sort_val = sv
                except (TypeError, ValueError, KeyError):
                    sort_val = missing_sort_val
            method_rows.append(row)
        # Handle dotless metric (e.g. 'calibration_loss')
        if not sort_sep and best:
            try:
                sv = (
                    float(metrics._get(best, sort_metric))
                    if metrics._get(best, sort_metric) is not None
                    else missing_sort_val
                )
                if math.isnan(sv):
                    sv = missing_sort_val
                sort_val = sv
            except (TypeError, ValueError):
                sort_val = missing_sort_val
        h_row = {"row": model}
        hp = best.get("applied_hyperparameters", {}) if best else {}
        for k in all_hp_keys:
            h_row[k] = metrics._fmt(hp[k]) if k in hp else ""
        grouped.append((sort_val, method_rows, h_row))

    _sort_grouped(grouped, order, lower_is_better)
    for _, method_rows, h_row in grouped:
        metric_rows.extend(method_rows)
        hp_rows.append(h_row)

    return metric_rows, hp_rows, all_hp_keys, display_columns


def _generate_html(dataset, metric, by_model, output_path, unlabeled=False, order=None):
    metric_rows, hp_rows, hp_keys, display_columns = _build_summary(
        by_model, metric, unlabeled=unlabeled, order=order
    )
    template = Template(_TEMPLATE.read_text(encoding="utf-8"))
    html = template.render(
        dataset=dataset,
        metric=cli.metric_display(metric),
        display_columns=display_columns,
        metric_rows=metric_rows,
        hp_rows=hp_rows,
        hp_keys=hp_keys,
    )
    with open(output_path, "w") as f:
        f.write(html)
    print(f"HTML report written to {output_path}")


def _draw_table_page(pdf, title, columns, rows):
    """Draw a single table as a matplotlib figure and save to the PDF."""
    n_rows = len(rows)
    n_cols = len(columns)

    fig_height = max(2.5, 0.35 * (n_rows + 2))
    fig, ax = plt.subplots(figsize=(max(10, 1.5 * n_cols), fig_height))
    ax.axis("off")
    ax.set_title(title, fontsize=11, fontweight="bold", pad=8, loc="left")

    cell_data = [[str(row.get(c, "")) for c in columns] for row in rows]
    table = ax.table(
        cellText=cell_data,
        colLabels=columns,
        colWidths=[1.0 / n_cols] * n_cols,
        loc="center",
        cellLoc="center",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(7)
    table.scale(1, 1.3)

    for j in range(n_cols):
        cell = table[0, j]
        cell.set_facecolor("#3a5a8a")
        cell.set_text_props(color="white", fontweight="bold")

    plt.tight_layout()
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def _generate_pdf(dataset, metric, by_model, output_path, unlabeled=False, order=None):
    metric_rows, hp_rows, hp_keys, display_columns = _build_summary(
        by_model, metric, unlabeled=unlabeled, order=order
    )

    # Rename internal 'row' key to a display label
    for row in metric_rows:
        row["Model / method"] = row.pop("row")
    for row in hp_rows:
        row["Model"] = row.pop("row")

    with PdfPages(output_path) as pdf:
        _draw_table_page(
            pdf,
            title=f"Metrics — Dataset: {dataset}  (best by {cli.metric_display(metric)})",
            columns=["Model / method"] + display_columns,
            rows=metric_rows,
        )
        _draw_table_page(
            pdf,
            title=f"Hyperparameters — Dataset: {dataset}  (best by {cli.metric_display(metric)})",
            columns=["Model"] + hp_keys,
            rows=hp_rows,
        )

    print(f"PDF report written to {output_path}")
